### ISSUE TITLE
luci-app-mwan3 fails to install

### ISSUE THREAD

**Issue by valentt** [Adze1502/mwan#13]
I have downloaded packages and installed them on OpenWrt Barrier Breaker 14.07, but during the install I get this error:

Configuring luci-app-mwan3.
//usr/lib/opkg/info/luci-app-mwan3.postinst: line 4: default_postinst: not found
Collected errors:
- pkg_run_script: package "luci-app-mwan3" postinst script returned status 127.
- opkg_configure: luci-app-mwan3.postinst returned 127.

**Comment by fengkaungluanzhua** [comment]
i can't handle it too

**Comment by arfett** [comment]
@ fengkaungluanzhua
Too bad.

**Comment by fengkaungluanzhua** [comment]
@arfett 
Perform reset is great!!!

LOL

**Comment by arfett** [comment]
@fengkaungluanzhua 
You shouldn't be using this code repository. The newest mwan3 versions are in the official OpenWrt Packages repository.

https://github.com/openwrt/packages
