### ISSUE TITLE
iface_id desync

### ISSUE THREAD

**Issue by cblack-zonnit** [Adze1502/mwan#14]
In the mwan3 script it issues interface ID's a bit different from the way the other scripts do.  In particular, I ran across this bug when one of my network interfaces didn't have an ifname assigned to it yet.

https://github.com/Adze1502/mwan/blob/master/mwan3/files/usr/sbin/mwan3#L86

This line should probably be moved up above the [-z $device] check?

**Comment by Adze1502** [comment]
Yes, you are right. I will fix this. Thnx for noticing.

**Comment by Adze1502** [comment]
Fixed in 1.4-25 version. The 1.5 release will be fixed soon.
