### ISSUE TITLE
An mwan brother?

### ISSUE THREAD

**Issue by drsound** [Adze1502/mwan#15]
Not a real issue, I just would like to get you informed about a project I've just released, very similar to your: https://github.com/drsound/fault_tolerant_router
The more, the better!

**Comment by Adze1502** [comment]
Nice! Let’s see if i can steal some nice new ideas ;)

If you ever need any help, i suck at programming, but i am an expert on linux routing.

—
Kind regards,
Jeroen Louwes

**Comment by drsound** [comment]
Well, it would be interesting to see if we used a different approach on connection/packet marking and so on. If you like, just run my "generate_config" and "generate_iptables", these steps can needn't be run on a real router with real interfaces: the output is quite heavily commented and easy to understand. I will try mwan3 in next days too.

**Comment by drsound** [comment]
Slashdot just accepted my article, commenters are bashing me! ;-)
http://linux.slashdot.org/story/15/03/03/1910206/linux-and-multiple-internet-uplinks-a-new-tool
I have no time for answer now, maybe tomorrow...
BTW lot of solutions I wasn't aware of are popping out.
