### ISSUE TITLE
ipset option ignored?

### ISSUE THREAD

**Issue by jscinoz** [Adze1502/mwan#16]
According to the [documentation](http://wiki.openwrt.org/doc/howto/mwan3#stickiness_and_ipset), it should be possible to route based on destination IP addresses in a preconfigured ipset.

Sadly, this appears to be untrue - a rule containing no other qualifiers besides an ipset option matches all outgoing packets. Looking through the source, it appears that matching based on ipsets isn't actually implemented - I can't see any match-set iptables rules being created anywhere.

Is the documentation incorrect, or am I overlooking something here?

**Comment by Adze1502** [comment]
Keep in mind that ipset support is available from version 1.6-1. Which version are you running?

1.6.1 is only available at the openwrt/package repository. This repository is unmaintained.

**Comment by arfett** [comment]
Perhaps the readme on this repo should be updated to reflect that it is unmaintained and should no longer be used.

**Comment by jscinoz** [comment]
Ah, that would explain it then, I have version 1.5-10. Oddly this is from an OpenWRT image built only yesterday, so I would have expected it to be the latest available. Do I need to do something special to get 1.6-1?

**Comment by jscinoz** [comment]
Ah, disregard that. My feeds.conf was referring to an old branch. My apologies for wasting anyone's time.

**Comment by Adze1502** [comment]
@arfett : the readme already has this info...

**Comment by arfett** [comment]
I'd say this issue shows that it may be a little ambiguous. Perhaps the very first thing should say this repository is unmaintained and should not be used and we recommend users use the OpenWrt/packages repository?
