### ISSUE TITLE
Incompatibility with Wifidog (captive portal)

### ISSUE THREAD

**Issue by pocha** [Adze1502/mwan#18]
I recently setup mwan3 & Wifidog on TP Link 1043 ND with Openwrt version - CC. 

On user authentication Wifidog runs following commands 

```
iptables -t mangle -A WiFiDog_br-lan_Incoming -d 192.168.9.157 -j ACCEPT
iptables -t mangle -A WiFiDog_br-lan_Outgoing -s 192.168.9.157 -m mac --mac-source a0:99:9b:02:8b:19 -j MARK --set-mark 2
```

Now the commands are suppose to whitelist the client `192.168.9.157` so the internet starts to work. Ping from the client still keep getting dropped & I suspect its something to do with mwan.

**Comment by arfett** [comment]
Please use MWAN software from the OpenWRT Packages repository. Please also
close this bug report and open a new issue in the OpenWrt Packages section
of Github. We do not monitor the "Adze1502/mwan" section of Github and you
will get more help from others at the official OpenWrt area.
